uinput: remove initialization of .time.* in static input_event
time.tv_usec and tv_sec are apparently not available any more on 32-bit
archs, possibly due to some year 2038 thing?

../buffyboard/uinput_device.c:35:8: error: 'struct input_event' has no member named 'time'
   35 |       .time.tv_usec = 0,
      |        ^~~~

This works around it by removing the explicit initialization of these
members of the input_event struct, since static int/float vars in C are
automatically initialized to 0.